Added mechanism to define custom levels at startup
lunarmodules/lualogging pull request #4
Opened 2020-08-16 23:50 UTC by aryajur

This will allow creating custom levels at startup. The default functionality remains the same. The added functionality is for optional use to allow customization of the logging levels.

2020-08-18 07:03 UTC, Tieske requested changes
thx! I like this flexibility. Can you take care of the comments? (style issues only)

Additionally please add;

- update to the docs
- changelog/history entry

2020-08-18 07:03 UTC, Tieske commented on src/logging.lua
> +}
not part iof this PR, but can you please fix the indentation here? and remove the newline at line 19

2020-08-18 07:03 UTC, Tieske commented on src/logging.lua
> +"DEBUG",
needs one more indentation level

2020-08-18 07:03 UTC, Tieske commented on src/logging.lua
> +-- @param levels optional table of custom logging levels
```suggestion
-- @param levels optional array of custom logging levels
```

2020-08-18 07:03 UTC, Tieske commented on src/logging/console.lua
> +  params = logging.getDeprecatedParams({ "logPattern","levels" }, params, ...)
please use a space after a comma, this has multiple occurences (this entire file is not consistent, but new code should probably be, thx!)

2020-08-18 07:26 UTC, Tieske commented on src/logging.lua
> +	end
I think we should not be using the provided table, but create a copy. While copying, we should convert all entries to uppercase.

and at the end of the `new` function we should verify that non of the names (in either uppercase or lowercase format) collides with an existing field on the new `logger` object. For example if we provide a level "LOG", or "APPEND" then the injected functions will become `logger:log()`, or `logger:append()`, which will override the existing properties/functions.

2020-08-18 16:24 UTC, aryajur commented
Ok, will fix these and resubmit

2020-08-19 04:13 UTC, aryajur commented
Ok I think I got everything. Please let me know if I missed something.

2020-08-19 19:40 UTC, Tieske commented
@aryajur I made some changes and pushed some extra commits, please check and let me know what you think.

2020-08-19 22:29 UTC, aryajur commented
Looks much better thanks

2020-08-20 07:55 UTC, Tieske approved these changes

2020-08-20 07:56 UTC, merged

2021-03-22 19:36 UTC, Tieske commented
@aryajur today I released version `1.5.0`, including this change, but had so much trouble that I had to revert it in `1.5.1`.

The problem is that the log-level constants are not only on the logger but also on the main module. For many years they were only on the main module, so a lot of code relies on that.

The change as it was did NOT set any constants on the main module, which was a major breaking change that went unnoticed. But then when trying to make this change work, whenever levels are changed, we need to change the globals as well on the main module. And that is a major issue, because it will break other loggers.

So really saw no alternative but to undo the change.

2021-03-22 23:33 UTC, aryajur commented
@Tieske  I dont follow. I see the constants at logging.lua. Where else do they exist?

2021-03-23 01:03 UTC, Tieske commented
For many years the constants were only available on the module table (hence globals). This PR changed it such that they were only available on the created logger objects.
All old code relying on them to be available on the module now failed (and there is a lot, since for a long time that was the only place you could get them)

2021-03-23 02:27 UTC, aryajur commented
I understand it better. I don't see why we cannot add it on the module table as well. It is a simple fix. I can create a pull request if you would like to explore it.

2021-03-23 13:07 UTC, Tieske commented
when starting the lib, there are 5 constants; DEBUG, ERR, WARN, etc. Each with their numeric index; 1 to 5.

If you add custom log levels, say one on each end, so we keep the 5 but have 1 lower, and one higher. The indexes become 1 to 7. The original 5 will have been shifted by 1.

Now any library that doesn't dynamically use the constants; eg, does this
```lua
local DEBUG = logging.DEBUG  -- caching the value at module level for example
...
logger:log(DEBUG, msg)
```
instead of this:
```lua
logger:log(logging.DEBUG, msg)
```
Will now break because the cached variable will not reflect the changes in the log levels.

2021-03-23 13:10 UTC, Tieske commented
luasyslog does this: https://github.com/lunarmodules/luasyslog/blob/main/syslog.lua#L5-L11

which;
1. has the problem described above
2. cannot deal with dynamic changing levels 

Anyway you look at it, it seems a massive breaking change...

2021-03-23 13:11 UTC, Tieske commented
Can you explain the use case? What problem are you trying to solve?

2021-03-23 16:13 UTC, aryajur commented
So the way I saw it was custom log levels were optional which provided flexibility to users to create their own log levels. The programs that were using the default ones would not notice the difference because they would never implement their custom levels. 
    The only problem understood with your example is that we did not define the levels in logging when the module was required. This can be easily fixed by initializing the levels in logging as they were done before (and now in 1.5.1). If a project defines its own levels when calling the **new** function then the default can be overwritten and this new program would know that since it is defining its own levels it cannot cache the levels before defining them obviously.
     In the end the aim was always to have this functionality as a non breaking change so that new projects would have the option to create their own levels if needed for the project.

As an example, one way I used it was by creating a custom level called TRANSMIT. This would be logged whenever my code transmitted a particular type of information to the server. A custom log level here was useful to allow another program to parse this log and extract all the TRANSMIT packet history and look at it.

This is just 1 example, I can only imagine that adding this functionality makes it very accommodating to do more creative things.

2021-03-23 18:01 UTC, Tieske commented
That should not be dealt with by the log levels, but by serialising the message component in a parsable format. And even then it's using the log system as a message bus, both very bad designs imho.

2021-03-23 19:18 UTC, aryajur commented
The problem with log levels is that they may not always be as expressive as one would like. Adding flexibility is I think a good idea in my opinion. It is not using it as a message bus but as a log record (which for one instance can be used for record keeping as well) of what was done and using a custom log level removes the complication of making the message serializable in a different way which I think would be a bad design by moving away from something that could be done in a standard way.
      But in any case it seems we disagree on this.  I will have to use my fork or rename it I think to remove confusion.

2021-03-24 01:05 UTC, daurnimator commented
log levels *shouldn't* be expressive; anything more than the list of levels from syslog should be unsupported IMO.           

> 0       Emergency: system is unusable
> 1       Alert: action must be taken immediately
> 2       Critical: critical conditions
> 3       Error: error conditions
> 4       Warning: warning conditions
> 5       Notice: normal but significant condition
> 6       Informational: informational messages
> 7       Debug: debug-level messages


I think what you're looking for @aryajur  is what is more widely known as "log scopes" rather than log levels

2021-03-24 02:49 UTC, aryajur commented
I am till not certain why you would want to limit that if the app would want to implement their own expressiveness and implementation does not require doing something extremely complicated. To me this sounds like Lua should implement OOP in a certain way and not give user's the flexibility to implement it the way they want. I'm sorry, I just don't see it aligned by the nature of Lua where you give mechanisms and allow the user to setup things they want to.

2021-03-24 08:57 UTC, Tieske commented
> That should not be dealt with by the log levels, but by serialising the message component in a parsable format. And even then it's using the log system as a message bus, both very bad designs imho.

This was more in response to your use case, if you want to use the logging system for this purpose, that's entirely up to you in the end.
I'm not opposed to making the levels flexible, my worries are about the breaking nature of it.

The constants on the module level are globals, and hence should never be changed. A solution to this (breaking) would be to no longer add the constants on the module, only on the created logger instances.
Maybe add them only to the module as a single list, eg "DEFAULT_LEVELS", which makes clear they are defaults only and will never be updated, and should not be used either since they might de different on a logger.

2021-03-24 15:11 UTC, aryajur commented
@Tieske yes those could be other ways that can be done. Thank you for discussing it.