Provide verbose error message when formatting fails
lunarmodules/lualogging pull request #6
Opened 2020-09-08 09:07 UTC by ynezz

Currently if the formatting of the log message fails it's quite hard to
find the source of the failure as one can find only following message in
the logs:

```lua
DEBUG Error formatting log message: bad argument #1 to '?' (string expected, got no value)
```

This patch adds stack trace to the error message which should make it
more clear where to find the source of the problem:

```lua
DEBUG Error formatting log message: bad argument #1 to '?' (string expected, got no value) | generic.lua:153: in function 'func' | generic.lua:166: in main chunk | test.lua:15: in main chunk
```

2020-09-08 20:48 UTC, Tieske requested changes
thx, very nice contribution. Can you have a look at the comments?

2020-09-08 20:48 UTC, Tieske commented on tests/generic.lua
> +end
👏

2020-09-08 20:48 UTC, Tieske commented on src/logging.lua
> +      end
I think this creates a new closure on each call. It would be more efficient if the function `error_handler` was moved out of `LOG_MSG`.

2020-09-09 12:09 UTC, ynezz commented
@Tieske should be done

2020-09-11 08:25 UTC, Tieske commented
@ynezz I pushed an extra commit, removing the pack/unpack operation. wdyt?

2020-09-11 08:31 UTC, ynezz commented
> wdyt?

Cool, didn't know, that this is possible, thanks a lot!

2020-09-11 08:41 UTC, merged

2020-09-11 08:41 UTC, Tieske commented
👍  thx for the contribution @ynezz !